apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
      deployedAt: "1768137820"
  name: location-app
  namespace: prpo-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-app
  template:
    metadata:
    annotations:
      deployedAt: "1768137820"
    annotations:
      deployedAt: "1768137616"
      labels:
        app: location-app
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: location-app
        image: prporegistry.azurecr.io/location-service:4f3d6c2b036e28005ed5b96fd8a83f3dd9bb0356
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: locations-db
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: locations-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: locations-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: locations-secret
              key: DB_NAME
---
apiVersion: v1
kind: Service
metadata:
    annotations:
      deployedAt: "1768137820"
    annotations:
      deployedAt: "1768137616"
  name: location-app
  namespace: prpo-microservices
spec:
  type: ClusterIP
  selector:
    app: location-app
  ports:
    - port: 8080
      targetPort: 8080

