name: build and deploy

on:
  push:
    branches: [ main, test ]

env:
  acr_login_server: prporegistry.azurecr.io
  image_name: location-service

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: login to acr
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
     
      - name: Build and push Docker image (no cache)
        run: |
          docker build --no-cache -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest 
      - name: Update Kubernetes manifest
        run: |
          sed -i "s|image: .*/location-service:.*|image: ${ACR_LOGIN_SERVER}/${IMAGE_NAME}:latest|" k8s/deployment.yaml
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/deployment.yaml
          git commit -m "Update image to ${{ github.sha }}" || exit 0
          git push 
